<a href="https://colab.research.google.com/github/kmardamb/DATA-205-Spring-2026/blob/main/Assignment_2_Data_Wrangling_with_pandas_Data201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2 – Data Wrangling with pandas

*(Based on Class 2 – pandas for R users)*

------------------------------------------------------------------------

## Learning Objectives

By completing this assignment, you should be able to:

-   Use pandas equivalents of `dplyr` verbs:
    -   `filter()` → boolean indexing / `.loc[]`
    -   `mutate()` → `.assign()`
    -   `group_by()` → `.groupby()`
    -   `summarise()` → `.agg()`
    -   `arrange()` → `.sort_values()`
-   Apply boolean logic correctly using `&` and `|`
-   Use **method chaining** for readable, step-by-step transformations
-   Create grouped summary tables with multiple statistics

------------------------------------------------------------------------

## Dataset

Use the provided dataset: `housing.csv`

``` python
import pandas as pd
df = pd.read_csv("housing.csv")
```

------------------------------------------------------------------------

# Part A – Core Wrangling (Method Chaining Required)

Using **one chained expression**, create a summary table that:

1.  Keeps only observations where `price > 250000`
2.  Keeps only homes with `size > 1000`
3.  Creates a new variable:
    -   `price_per_sqft = price / size`
4.  Groups by `neighborhood`
5.  Computes:
    -   mean of `price_per_sqft`
    -   median of `price_per_sqft`
    -   count of homes
6.  Sorts the result by mean `price_per_sqft` (descending)

### Requirements

-   Do NOT create intermediate variables (`df2`, `df3`, etc.)
-   Use `.assign()` to create new variables
-   Use `.agg()` with named aggregation
-   **Do not use `reset_index()`** (we did not cover it yet)

### Output format note

After `groupby()`, pandas will put `neighborhood` in the *index*. That
is OK for this assignment. Your final output can look like a table where
`neighborhood` is on the left as the index.

### Deliverable

-   Paste your code
-   Show the final DataFrame output

------------------------------------------------------------------------

# Part B – Translation to dplyr

In a Markdown cell, write the equivalent **dplyr** code that performs
the same transformation.

Your R pipeline should include:

-   `filter()`
-   `mutate()`
-   `group_by()`
-   `summarise()`
-   `arrange()`

### Reflection (3–6 sentences)

Answer:

-   Which syntax feels clearer for you — pandas chaining or dplyr
    pipelines?
-   What feels similar between them?
-   What feels different?

------------------------------------------------------------------------

# Part C – Boolean Logic Debugging

The following code produces an error:

``` python
df[df["price"] > 250000 & df["size"] > 1000]
```

### Tasks

1.  Fix the code.
2.  Explain **why** the error occurs.
3.  Rewrite the filter using `.query()` instead.

------------------------------------------------------------------------

# Part D – Short Concept Questions

Answer briefly (2–4 sentences each):

1.  Why must we wrap each condition in parentheses when using `&` in
    pandas?
2.  What is the advantage of method chaining over creating many
    temporary DataFrames?
3.  In `.agg(mean_price=("price", "mean"))`, what does `"price"`
    represent? What does `"mean"` represent?
4.  When you `groupby("neighborhood")`, why does `neighborhood` appear
    on the left (index) in the result table?

------------------------------------------------------------------------

## Optional Extension (Extra practice)

Create a second summary table grouped by `type` that reports: - mean
`price` - median `price` - count of listings (Use method chaining
again.)

In [8]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Reben80/Data201/main/Dataset/housing.csv")

df.head()

   listing_id    price         size  bedrooms neighborhood          type
0      100001  1500000  1280.741760       1.0       Suburb     Townhouse
1      100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2      100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3      100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4      100005  1500000  1243.751760       1.0     Downtown   MultiFamily

## PART A

In [10]:
(
    df
    .query("price > 250000 and size > 1000")
    .assign(price_per_sqft=lambda d: d["price"] / d["size"])
    .groupby("neighborhood")
    .agg(mean_price_per_sqft=("price_per_sqft", "mean"), median_price_per_sqft=("price_per_sqft", "median"), home_count=("price_per_sqft", "size"))
    .sort_values("mean_price_per_sqft", ascending=False)
)

              mean_price_per_sqft  median_price_per_sqft  home_count
neighborhood
Downtown               977.820905            1001.557049          99
Midtown                921.141446             901.992377          92
Suburb                 861.917078             836.878644         157
Uptown                 860.935608             843.653468          99
Waterfront             849.508891             792.663291          48

## PART B

In [ ]:
library(dplyr)

df %>%
  filter(price > 250000, size > 1000) %>%
  mutate(price_per_sqft = price / size) %>%
  group_by(neighborhood) %>%
  summarise(mean_price_per_sqft = mean(price_per_sqft), median_price_per_sqft = median(price_per_sqft), count_homes = n()) %>%
  arrange(desc(mean_price_per_sqft))

Since I'm more used to R studio from Data science courses R syntax makes more sense to me. The syntax from pandas does clean up a lot of the unessecary piping that's used in R and they are similar in the ability to sequence the filtering process. The difference between the two languages is the syntax.

## PART C

In [11]:
df[df["price"] > 250000 & df["size"] > 1000]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [12]:
## Corrected Code
df[(df["price"] > 250000) & (df["size"] > 1000)]

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

In [13]:
df.query("price > 250000 and size > 1000")

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

The error occurs when you don't include parentheses in the df statement.

## PART D

## 1.

Parentheses are used to avoid evaluating the function in the wrong order, that can be properly combined with the & function.

## 2.

Method chaining keeps the workflow in a manageable pipeline for multiple uses of the data set at times needed later.

## 3.

Price is the column you want to summarize from the data set, and mean is the aggregation function that summarizes the value into one.

## 4.

Instead of multiple neighborhood columns it combines the columns to have one single defining label for the data set.